# User.create!([
#   {email: "matt@test.com", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2018-04-16 01:32:55", last_sign_in_at: "2018-04-15 17:51:44", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
# ])
Category.create!([
  {name: "Flyfishing"},
  {name: "Rainbow Trout"},
  {name: "Brown Trout"},
  {name: "Outdoors"},
  {name: "Girls Fly Fishing"},
  {name: "Brook Trout"},
  {name: "Chum"},
  {name: "Grayling"},
  {name: "Fly Rod"},
  {name: "Char"},
  {name: "Tiger Trout"},
  {name: "Stream Fishing"},
  {name: "Utah Fly Fishing"},
  {name: "Fish Flop Friday"},
  {name: "Gear Review"},
  {name: "Dry Flies"},
  {name: "Fishing With Dogs"},
  {name: "Nymph Fishing"},
  {name: "Gear"},
  {name: "Salmon"},
  {name: "Pocket Water"},
  {name: "Night Fly Fishing"},
  {name: "Fly On The Mountain"},
  {name: "Simms"},
  {name: "Streamer Fishing"}
])
Hashtag.create!([
  {name: "flyfishing"},
  {name: "trout"},
  {name: "raibowtrout"},
  {name: "tightlines"},
  {name: "troutfishing"},
  {name: "browntrout"},
  {name: "outdoorsman"},
  {name: "flyfishingjunkie"},
  {name: "flygirl"},
  {name: "flyfish"},
  {name: "freshwaterfishing"},
  {name: "keepemwet"},
  {name: "flyfishingnation"},
  {name: "dryfly"},
  {name: "brooktrout"},
  {name: "flyfishingaddict"},
  {name: "fishpond"},
  {name: "fishingbuddy"},
  {name: "flyfishingphotography"},
  {name: "brookie"},
  {name: "slipperywhenwet"},
  {name: "chum"},
  {name: "grayling"},
  {name: "fishingspot"},
  {name: "flyrod"},
  {name: "fishingseason"},
  {name: "arcticchar"},
  {name: "letthemgosotheycangrow"},
  {name: "flyfishing_flygirls"},
  {name: "flyfishing_feature"},
  {name: "flylords"},
  {name: "nymphs"},
  {name: "brookies"},
  {name: "wadeforit"},
  {name: "fishingbuddies"},
  {name: "dryflyfishing"},
  {name: "flyfishinglife"},
  {name: "flyfisherman"},
  {name: "tigertrout"},
  {name: "flyfishingwoken"},
  {name: "flyfishinggear"},
  {name: "flyfishingjunky"},
  {name: "flyfishingisrad"},
  {name: "streams"},
  {name: "flyfishingporn"},
  {name: "flyfishingutah"},
  {name: "fishflopfriday"},
  {name: "flyfishinggirls"},
  {name: "flyfishingfanatic"},
  {name: "rainbowtroutfishing"},
  {name: "gearreview"},
  {name: "flyfishingadventures"},
  {name: "graylingfishing"},
  {name: "flyfishingforlife"},
  {name: "flyfishingdaily"},
  {name: "chumsalmon"},
  {name: "flyfishinggirl"},
  {name: "flyfishingbum"},
  {name: "flyfishingtrout"},
  {name: "browntroutfishing"},
  {name: "flyaddict"},
  {name: "flyfishingislife"},
  {name: "slipperyfish"},
  {name: "pocketwater"},
  {name: "graylingparade"},
  {name: "nightflyfishing"},
  {name: "flyonthemountain"},
  {name: "repyourwater"},
  {name: "optoutside"},
  {name: "troutbum"},
  {name: "goatworthy"},
  {name: "seewhatsoutthere"},
  {name: "fishinglife"},
  {name: "fishingdaily"},
  {name: "instafishing"},
  {name: "findyourwater"},
  {name: "simms"},
  {name: "fishexploreconserve"},
  {name: "mountainangler"},
  {name: "cheekyflyfishing"},
  {name: "teamwhyknot"},
  {name: "whyknotfishing"},
  {name: "steamers"},
  {name: "onthefly"},
  {name: "meateater"},
  {name: "ontheswing"},
])
UserHashtagCategory.create!([
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'trout'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'raibowtrout'), category: Category.find_by(name: 'Rainbow Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'tightlines'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'troutfishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'browntrout'), category: Category.find_by(name: 'Brown Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'outdoorsman'), category: Category.find_by(name: 'Outdoors')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingjunkie'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flygirl'), category: Category.find_by(name: 'Girls Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfish'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'freshwaterfishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'keepemwet'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingnation'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'dryfly'), category: Category.find_by(name: 'Dry Flies')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'brooktrout'), category: Category.find_by(name: 'Brook Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingaddict'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishpond'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingbuddy'), category: Category.find_by(name: 'Fishing With Dogs')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingbuddy'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingphotography'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'brookie'), category: Category.find_by(name: 'Brook Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'slipperywhenwet'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'chum'), category: Category.find_by(name: 'Chum')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'grayling'), category: Category.find_by(name: 'Grayling')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingspot'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyrod'), category: Category.find_by(name: 'Fly Rod')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyrod'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingseason'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'arcticchar'), category: Category.find_by(name: 'Char')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'letthemgosotheycangrow'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishing_flygirls'), category: Category.find_by(name: 'Girls Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishing_feature'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flylords'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'nymphs'), category: Category.find_by(name: 'Nymph Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'brookies'), category: Category.find_by(name: 'Brook Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'wadeforit'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingbuddies'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingbuddies'), category: Category.find_by(name: 'Fishing With Dogs')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'dryflyfishing'), category: Category.find_by(name: 'Dry Flies')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishinglife'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfisherman'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'tigertrout'), category: Category.find_by(name: 'Tiger Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingwoken'), category: Category.find_by(name: 'Girls Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishinggear'), category: Category.find_by(name: 'Gear')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingjunky'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingisrad'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'streams'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'streams'), category: Category.find_by(name: 'Stream Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingporn'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingutah'), category: Category.find_by(name: 'Utah Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishflopfriday'), category: Category.find_by(name: 'Fish Flop Friday')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishinggirls'), category: Category.find_by(name: 'Girls Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingfanatic'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'rainbowtroutfishing'), category: Category.find_by(name: 'Rainbow Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'gearreview'), category: Category.find_by(name: 'Gear')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'gearreview'), category: Category.find_by(name: 'Gear Review')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingadventures'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'graylingfishing'), category: Category.find_by(name: 'Grayling')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingforlife'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingdaily'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'chum'), category: Category.find_by(name: 'Salmon')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'chumsalmon'), category: Category.find_by(name: 'Salmon')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'chumsalmon'), category: Category.find_by(name: 'Chum')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishinggirl'), category: Category.find_by(name: 'Girls Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'browntroutfishing'), category: Category.find_by(name: 'Brown Trout')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingbum'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingtrout'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyaddict'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyfishingislife'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'slipperyfish'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'pocketwater'), category: Category.find_by(name: 'Pocket Water')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'graylingparade'), category: Category.find_by(name: 'Grayling')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'nightflyfishing'), category: Category.find_by(name: 'Night Fly Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flyonthemountain'), category: Category.find_by(name: 'Fly On The Mountain')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'repyourwater'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'optoutside'), category: Category.find_by(name: 'Outdoors')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'troutbum'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'goatworthy'), category: Category.find_by(name: 'Outdoors')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'seewhatsoutthere'), category: Category.find_by(name: 'Outdoors')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishinglife'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishingdaily'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'instafishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'findyourwater'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'simms'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'simms'), category: Category.find_by(name: 'Simms')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'fishexploreconserve'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'mountainangler'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'cheekyflyfishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'teamwhyknot'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'whyknotfishing'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'steamers'), category: Category.find_by(name: 'Streamer Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'onthefly'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'meateater'), category: Category.find_by(name: 'Flyfishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'meateater'), category: Category.find_by(name: 'Streamer Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'ontheswing'), category: Category.find_by(name: 'Streamer Fishing')},
  {user_id: 2, hashtag: Hashtag.find_by(name: 'flytyingmaterials'), category: Category.find_by(name: 'Fly Tying')}  
])

